apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vm-instance
  namespace: victoria-metrics
spec:
  retentionPeriod: "1" # months
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
---
# select all scrape objects in specific namespace (my-namespace)
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vm-agent
  namespace: victoria-metrics
spec:
  remoteWrite:
    - url: "http://vmsingle-vm-instance.default.svc:8428/api/v1/write"
  scrapeInterval: 30s
  serviceScrapeNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: newcastle--runtime-devel
  podScrapeNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: newcastle--runtime-devel

