apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by=openshift-gitops  # needed for Openshift
  name: cert-manager-operator
---
# Tells OLM which namespaces to monitor
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  labels:
    argocd.argoproj.io/managed-by=openshift-gitops  # needed for Openshift
  name: cert-manager-operator
  namespace: cert-manager-operator
spec:
  targetNamespaces:
  - cert-manager-operator
---
# Subscription
# This will deploy cert-manager in the 'cert-manager' namespace
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-cert-manager-operator
  namespace: cert-manager-operator
spec:
  channel: stable-v1 # Or the specific version you need
  installPlanApproval: Automatic
  name: openshift-cert-manager-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
