# Operator namespaces

# Application namespaces
---
apiVersion: v1
kind: Namespace
metadata:
  name: devel
---
apiVersion: v1
kind: Namespace
metadata:
  name: stage
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
