apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 02-openshift-operators
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-10" # Run this first!
spec:
  project: default
  source:
    repoURL: https://github.com/thescouser89/gitops-play
    path: 01-openshift-operators
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true # Important for CRDs that don't exist yet
      - RespectIgnoreDifferences=true
