apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: openshift-gitops  # needed for Openshift
  name: cnpg-system
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cnpg-operatorgroup
  namespace: cnpg-system
spec: {}    # Empty spec = watch all namespaces (recommended for CNPG)
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  channel: stable-v1
  name: cloudnative-pg
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
