apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10" # Run this first!
spec:
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: v1.15.0 # Use a specific version
    helm:
      parameters:
        - name: crds.enabled
          value: "true" # Required for cert-manager to work
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
